name: snapfinance
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  camerawesome: ^1.4.0
  device_info_plus: ^8.2.0
  flutter:
    sdk: flutter
  flutter_vnd_keyboard:
    git:
      url: https://github.com/daohoangson/flutter-vnd_keyboard
      ref: 66f5326c896d60eec3676fda72925ae634f54498
  google_mlkit_text_recognition: ^0.5.0
  intl: ^0.18.1
  path_provider: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/placeholders/
  uses-material-design: true
