name: snapfinance
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  camerawesome: ^1.4.0
  device_info_plus: ^8.2.0
  equatable: ^2.0.5
  firebase_analytics: ^9.0.0-dev.2 # https://github.com/firebase/flutterfire/blame/b81a6eb88aade38ec802dcdf18939b522e61ec8e/packages/firebase_analytics/firebase_analytics/pubspec.yaml
  firebase_auth: ^3.2.0 # https://github.com/firebase/flutterfire/blame/b81a6eb88aade38ec802dcdf18939b522e61ec8e/packages/firebase_auth/firebase_auth/pubspec.yaml
  firebase_core: ^1.15.0 # https://github.com/firebase/flutterfire/commit/faaf449624ff4081cbbc0f241fec3134492cbdb3 for https://github.com/firebase/firebase-ios-sdk/commit/f5038c2df5a636a2144519e70b25433d188638e2 for GTMSessionFetcher/Core v1
  firebase_core_platform_interface: 4.5.1
  firebase_crashlytics: ^2.3.0 # https://github.com/firebase/flutterfire/blame/b81a6eb88aade38ec802dcdf18939b522e61ec8e/packages/firebase_crashlytics/firebase_crashlytics/pubspec.yaml
  firebase_storage: ^10.1.0 # https://github.com/firebase/flutterfire/blame/b81a6eb88aade38ec802dcdf18939b522e61ec8e/packages/firebase_storage/firebase_storage/pubspec.yaml
  flex_color_scheme: ^7.0.4
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_vnd_keyboard:
    git:
      url: https://github.com/daohoangson/flutter-vnd_keyboard
      ref: f98496e6c8560a8b41fd2701731e52bf44118eb7
  google_mlkit_text_recognition: ^0.5.0 # https://stackoverflow.com/questions/73992337/flutter-build-is-ios-error-xcode-undefined-symbol-objc-msgsend
  intl: ^0.17.0
  path: ^1.8.2
  path_provider: ^2.0.14
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/placeholders/
  uses-material-design: true
